[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
actix-rt = "2.5.0"
actix-files = "0.5.0"
serde = "1.0.130"
chrono = "0.4.19"
